apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lnvrq2ybj-go 
  janus-idp.io/tekton: lnvrq2ybj-go
  backstage.io/kubernetes-id: lnvrq2ybj-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lnvrq2ybj-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml