apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lnvrq2ybj-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lnvrq2ybj-go 
  name: lnvrq2ybj-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lnvrq2ybj-go 
